[[dialogue]]
event = 84
page = 1
command = 2
original = '''
\c[10]Händler\c[0]: Ich habe hier erstklassige Ausrüstung 
aus Helnovien. Sie wurde aus hochwertigen 
Eisen  hergestellt. 
'''
patched = '''
\c[10]Merchant\c[0]: I have top-tier equipment from
Helnovien here. It was made from the
highest quality iron.
'''

[[dialogue]]
event = 84
page = 1
command = 5
original = '''
\c[10]Händler\c[0]: Es wird noch eine Weile dauern bis 
diese Ware West-Brigantia erreichen wird, also 
zuschnappen!
'''
patched = '''
\c[10]Merchant\c[0]: It'll take a while until this shipment
reaches West Brigantia, so grab some while
you still can!
'''

[[dialogue]]
event = 87
page = 1
command = 11
original = '''

Dies ist ein \c[11]Speicherpunkt\c[0].
'''
patched = '''

This is a \c[11]save point\c[0].
'''

[[dialogue]]
event = 87
page = 1
command = 13
original = '''

Wenn man auf solch einen steht, kann man \c[11]den
Spielstand speichern\c[0].
'''
patched = '''

When you stand on one of these, you can
\c[11]save the game\c[0].
'''

[[dialogue]]
event = 87
page = 1
command = 16
original = '''

Öffne dazu das \c[11]Menu\c[0] mit \c[11]Esc\c[0] und wähle
dann \c[11]Speichern\c[0].
'''
patched = '''

To do this, open the \c[11]menu\c[0] using \c[11]Esc\c[0] and
then select \c[11]Save\c[0].
'''

[[dialogue]]
event = 87
page = 1
command = 19
original = '''

Auf der \c[11]Weltkarte\c[0] kann man übigens
immer speichern.
'''
patched = '''

Additionally, you can always save on
the \c[11]world map\c[0].
'''

[[text]]
event = 87
page = 1
command = 4
original = '''CorinePlat1'''
patched = '''Corine Plateau'''
