[[dialogue]]
event = 5
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: *mampf*\. Diescher 
Nudelschalat ischt vortrefflisch!\. Wirklisch.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: *nom*\. This pasta salad
is delicious!
'''

[[dialogue]]
event = 5
page = 1
command = 7
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Öhm, ich möchte dich ja 
ungern beim Essen stören\., aber 
hattest du nicht zu diesem Zeitpunkt 
ein Treffen?
'''
patched = '''
\c[1]\n[1]\c[0]: Um, I don't mean to disturb
you from your meal,\. but don't you
have a meeting right about now?
'''

[[dialogue]]
event = 5
page = 1
command = 13
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Oh ja, schtimmt...\.
Moment...\. OH! ischt es schon so schpät?\.
*schluck*\. Ohje, ich komme zu spät!
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Oh yeah, that's right...\.
Wait...\. OH! Is it already so late?\.
*swallow*\. Oh no, I'm late!
'''

[[dialogue]]
event = 6
page = 1
command = 3
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Hey!\. Wann 
kommt endlich mein Nachschub?
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Hey!\. When will my
order finally get here?
'''

[[dialogue]]
event = 7
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Hm?\. Stör mich 
nicht beim Essen...
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Hm?\. Don't bother me
while I'm eating...
'''

[[dialogue]]
event = 8
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Hm...\. ob es heute 
etwas Besonderes zum Nachtisch gibt?
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Hm...\. I wonder if there's
anything special for dessert today?
'''

[[dialogue]]
event = 9
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Kein Bier...\. Wieso 
gibt es hier kein Bier zu trinken?\. Args!
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: No beer...\. Why is there no
beer to drink here?\. Argh!
'''

[[dialogue]]
event = 9
page = 1
command = 7
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Bier macht träge, wenn man 
es zu oft trinkt.
'''
patched = '''
\c[1]\n[1]\c[0]: Beer makes you sluggish if
you drink it too often.
'''

[[dialogue]]
event = 9
page = 1
command = 10
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Hör nicht auf ihn, er hat keine 
Ahnung, wie es ist, ein kühles, 
frisches Bier zu trinken.
'''
patched = '''
\c[2]\n[2]\c[0]: Don't listen to him, he has
no idea what it's like to drink
a cool, fresh beer.
'''

[[dialogue]]
event = 9
page = 1
command = 14
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Außerdem ist das Bier hier 
nur vorübergehend alle.
'''
patched = '''
\c[2]\n[2]\c[0]: Besides, the beer is only
temporarily gone here.
'''

[[dialogue]]
event = 10
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: In letzter Zeit 
haben manche Soldaten immer öfter Essens-
wünsche an die Köche, die dann sogar erfüllt 
werden.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Recently, some soldiers have
made more and more requests to the cooks,
which are somehow fulfilled.
'''

[[dialogue]]
event = 10
page = 1
command = 6
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Und es werden 
immer mehr hier, die ihren speziellen Wunsch 
als Mahlzeit haben wollen.\. Das halten die Köche 
sicher nicht mehr lange aus. 
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: And there are more and more
people here who want their special request
fulfilled.\. The cooks definitely won't be
able to keep up with this for much longer.
'''

[[dialogue]]
event = 10
page = 3
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: In letzter Zeit 
haben manche Soldaten immer öfter Essens-
Wünsche an die Köche, die dann sogar erfüllt 
werden.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Recently, some soldiers have
made more and more requests to the cooks,
which are somehow fulfilled.
'''

[[dialogue]]
event = 10
page = 3
command = 6
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Und es werden 
immer mehr hier, die ihre speziellen Wunsch 
als Mahlzeit haben wollen.\. Das halten die Köche 
sicher nicht mehr lange aus. 
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: And there are more and more
people here who want their special request
fulfilled.\. The cooks definitely won't be
able to keep up with this for much longer.
'''

[[dialogue]]
event = 12
page = 2
command = 2
original = '''
\c[10]Köchin\c[0]: Es ist noch genug zu Essen da.\. Bedienen 
Sie sich.\. Wenn Sie einen speziellen Wunsch 
haben, sagen Sie mir Bescheid.
'''
patched = '''
\c[10]Cook\c[0]: There's still enough food for everyone.\.
Help yourself.\. If you have a special request,
please let me know.
'''

[[dialogue]]
event = 12
page = 2
command = 5
original = '''
\c[10]Köchin\c[0]: Bier ist allerdings derzeit alle...
'''
patched = '''
\c[10]Cook\c[0]: However, the beer is currently all gone...
'''

[[dialogue]]
event = 25
page = 2
command = 17
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Morgen Kumpel.\. Haste also 
doch wieder so lang geschlafen?
'''
patched = '''
\c[2]\n[2]\c[0]: Mornin'.\. You slept
so long again?
'''

[[dialogue]]
event = 25
page = 2
command = 20
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Ja...\. und jetzt verhungere ich 
fast.
'''
patched = '''
\c[1]\n[1]\c[0]: Yeah...\. and now I'm almost
starving.
'''

[[dialogue]]
event = 25
page = 2
command = 23
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Dacht' ich mir schon.\. Mir 
ging's genauso.\. Ich hab schon etwas 
für dich bestellt, nur leider hast 
du länger geschlafen als ich dachte.
'''
patched = '''
\c[2]\n[2]\c[0]: I thought so.\. I felt the same
way.\. I've already ordered something
for you, but unfortunately, you
slept longer than I expected.
'''

[[dialogue]]
event = 25
page = 2
command = 28
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Deswegen steht das Zeug hier 
schon ne ganze Weile und ist schon 
kalt geworden...
'''
patched = '''
\c[2]\n[2]\c[0]: That's why the stuff has been
here for quite a while and has gotten
cold...
'''

[[dialogue]]
event = 25
page = 2
command = 32
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Egal,\. Hauptsache es ist was zu 
Essen.
'''
patched = '''
\c[1]\n[1]\c[0]: No problem,\. as long as there's
something to eat.
'''

[[dialogue]]
event = 25
page = 2
command = 42
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Kento, Cibon?\.
Sir Vorento fragt nach euch.\. 
Ihr sollt bitte sofort zu ihm kommen.\. 
Er wartet wieder im 1. Lehrraum.\.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Kento, Cibon?\.
Sir Vorento requests you.\.
You should come to him immediately.\.
He is waiting in the 1st classroom again.\.
'''

[[dialogue]]
event = 25
page = 2
command = 46
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Ihr solltet eure 
Mahlzeit lieber auf später verschieben...\.
Ich geh dann wieder.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: You should postpone your
meal until later...\. Well,\. I'm off again.
'''

[[dialogue]]
event = 25
page = 2
command = 56
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: ...
'''
patched = '''
\c[1]\n[1]\c[0]: ...
'''

[[dialogue]]
event = 25
page = 2
command = 58
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Super, wahrscheinlich geht's 
um den neuen Auftrag.\. Lass uns 
hingehen, Kumpel!
'''
patched = '''
\c[2]\n[2]\c[0]: Sweet, it's probably about
our new order.\. Let's go!
'''

[[dialogue]]
event = 25
page = 2
command = 62
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: \s[4]Ich esse noch.
'''
patched = '''
\c[1]\n[1]\c[0]: \s[4]I'm still eating.
'''

[[dialogue]]
event = 25
page = 2
command = 69
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Das hat noch später Zeit!\. 
Lass uns gehen!
'''
patched = '''
\c[2]\n[2]\c[0]: There's time for that later!\.
Let's go already!
'''

[[dialogue]]
event = 25
page = 2
command = 77
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Ich hab aber noch Hunger!\. \s[5]Och 
Mann...\|\^
'''
patched = '''
\c[1]\n[1]\c[0]: I'm still hungry!\. \s[5]Oh man...\|\^
'''
