[[dialogue]]
event = 10
page = 1
command = 2
original = '''
\c[10]Wache\c[0]: Passt auf, in diesem Bereich tauchen hin 
und wieder Monster auf.\. Ihr solltet besser 
fliehen, wenn ihr mit denen nicht fertig werdet.
'''
patched = '''
\c[10]Guard\c[0]: Careful out there, monsters appear in this
area every now and then.\. You'd better escape if
you can't deal with them.
'''

[[dialogue]]
event = 122
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Wo kam bloß auf einmal dieses Wasser 
her?\. Ich hätt' schwören können, vor einigen Tagen 
konnte man hier noch frei und unbeschwert 
durchlaufen...
'''
patched = '''
\c[10]Prisoner\c[0]: Where'd all this water come from?\.
Could've sworn I could still walk freely without
a care over here just a few days ago...
'''

[[dialogue]]
event = 123
page = 1
command = 2
original = '''
\c[10]Gefangene\c[0]: Wie kam bitte diese Person da drüben 
über das Wasser?\. Ist sie etwas einfach 
durchgeschwommen?\. Manche Leute können es wirklich 
übertreiben...
'''
patched = '''
\c[10]Prisoner\c[0]: How'd that person get over the water
over there?\. Did he just swim a bit?\. Some people
really can go way too far with this mining...
'''

[[dialogue]]
event = 124
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 125
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 127
page = 1
command = 11
original = '''
\c[10]Pauamainer-Miglied\c[0]: Du hast es echt zustande 
gebracht, das Wasser abfließen zu lassen.\. Respekt!\.
Jetzt komme ich endlich zu dieser Erzstelle, ohne 
schwimmen zu müssen, danke sehr! 
'''
patched = '''
\c[10]Pauamainer Member\c[0]: You actually managed to drain
the water away.\. Respect!\. Now I can finally come
to this ore deposit without having to swim,
thanks a ton!
'''

[[dialogue]]
event = 127
page = 1
command = 15
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ach ja, natürlich bekommste 
dafür einen Ordnen.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Oh right, of course you'll get
a medallion for it.
'''

[[dialogue]]
event = 127
page = 1
command = 28
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ihr guckt so verdutzt.\. Wenn 
ihr mehr über uns und die Minen-Orden 
erfahren wollt, besucht einfach unseren 
Stützpunkt.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: You look so confused.\. If you
want to learn more about us and the miner
medallions, just visit our base.
'''

[[dialogue]]
event = 127
page = 1
command = 32
original = '''
\c[10]Pauamainer-Miglied\c[0]: Dieser befindet sich im 
mittleren Bereich der Mine.\. Fahrt beim nächsten 
Mal mit der Lore einfach rechts und dann 
geradeaus.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It's located at the center of
the mine.\. Next time on the railways, just go
right and then straight.
'''

[[dialogue]]
event = 127
page = 1
command = 38
original = '''
\c[10]Pauamainer-Miglied\c[0]: Glück auf!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Good luck!
'''

[[dialogue]]
event = 127
page = 1
command = 45
original = '''
\c[10]Pauamainer-Miglied\c[0]: Hm...\. jetzt, wo das Wasser 
weg ist, kann an sich jeder Minenarbeiter leicht 
zu dieser Stelle gelangen.\. Oh, oh.\. Wahrscheinlich 
muss ich mir bald etwas Neues suchen.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Hm...\. Now that the water is
gone, every miner can easily get to this point.\.
Uh oh.\. I'll probably have to find someplace
new very soon.
'''
