[[dialogue]]
event = 13
page = 1
command = 11
original = '''
\c[10]Pauamainer-Miglied\c[0]: Oh!\. Biste tatsächlich den 
langen Weg über die Klippen gegangen, nur um zu 
mir zu kommen?\. Nicht schlecht, nicht schlecht!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Oh!\. Did you actually go the
long way over the cliffs just to get to me?\.
Not bad, not bad!
'''

[[dialogue]]
event = 13
page = 1
command = 14
original = '''
\c[10]Pauamainer-Miglied\c[0]: Falls du wegen des Ordens 
kommst,\. tut mir Leid,\. aber die sind alle!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: If you've come for the
medallion,\. I'm sorry,\. but I'm all out!
'''

[[dialogue]]
event = 13
page = 1
command = 20
original = '''
\c[10]Pauamainer-Miglied\c[0]: Hehehe!\. Ein Scherz, ein 
Scherz!\. Natürlich hab ich noch Orden.\. Da, bitte 
sehr.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Hehehe!\. I'm joking, I'm joking!\.
Of course I still have the medallions.\. There you
go.
'''

[[dialogue]]
event = 13
page = 1
command = 34
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ihr guckt so verdutzt.\. Wenn 
ihr mehr über uns und die Minen-Orden 
erfahren wollt, besucht einfach unseren 
Stützpunkt.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: You look so confused.\. If you
want to learn more about us and the miner
medallions, just visit our base.
'''

[[dialogue]]
event = 13
page = 1
command = 38
original = '''
\c[10]Pauamainer-Miglied\c[0]: Dieser befindet sich im 
mittleren Bereich der Mine.\. Fahrt beim nächsten 
Mal mit der Lore einfach rechts und dann 
geradeaus.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It's located at the center of
the mine.\. Next time on the railways, just go
right and then straight.
'''

[[dialogue]]
event = 13
page = 1
command = 44
original = '''
\c[10]Pauamainer-Miglied\c[0]: Glück auf!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Good luck!
'''

[[dialogue]]
event = 13
page = 1
command = 51
original = '''
\c[10]Pauamainer-Miglied\c[0]: Wenn ihr wieder zurück wollt, 
müsst ihr diesen Weg zurückgehen.\. Ihr könnt dann 
den unteren Gang entlang laufen. Der führt dann 
wieder zum Anfang.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: If you want to go back, you'll
have to go back the way you came.\. You can then
hop down to the floor. Which then leads back
to the start.
'''

[[dialogue]]
event = 25
page = 1
command = 11
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ah!\. Ihr gehört also auch zu 
uns Bergsteigern unter den Minenarbeitern!\. Reife 
Leistung! \.Bekomme nicht so oft Besuch hier!\. Dafür 
gibt es nen Orden!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Ah!\. So you're one of us
mountaineers among the miners!\. Good job!\.
Don't get too many visitors around here!\.
Here's a medallion for that!
'''

[[dialogue]]
event = 25
page = 1
command = 26
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ihr guckt so verdutzt.\. Wenn 
ihr mehr über uns und die Minen-Orden 
erfahren wollt, besucht einfach unseren 
Stützpunkt.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: You look so confused.\. If you
want to learn more about us and the miner
medallions, just visit our base.
'''

[[dialogue]]
event = 25
page = 1
command = 30
original = '''
\c[10]Pauamainer-Miglied\c[0]: Dieser befindet sich im 
mittleren Bereich der Mine.\. Fahrt beim nächsten 
Mal mit der Lore einfach rechts und dann 
geradeaus.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It's located at the center of
the mine.\. Next time on the railways, just go
right and then straight.
'''

[[dialogue]]
event = 25
page = 1
command = 36
original = '''
\c[10]Pauamainer-Miglied\c[0]: Glück auf!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Good luck!
'''

[[dialogue]]
event = 25
page = 1
command = 43
original = '''
\c[10]Pauamainer-Miglied\c[0]: Das klingt zwar komisch, aber 
das hier ist der höchste Punkt in dieser Mine! \.
Davon bin ich überzeugt!\. Und wunderbares Erz gibt 
es hier, das sag ich dir, Kumpel!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It might sound strange, but
this is the highest point in this mine!\. I'm
convinced of that!\. And there's wonderful
ore here I tell you what!
'''

[[dialogue]]
event = 26
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Oh Mann, ich möchte bloß nicht zu nah 
an dieser Schlucht da arbeiten...\. Hast du eine 
Vorstellung, wie tief das ist?\. Also ich hab es 
nicht, ich weiß nur, dass es tief genug ist...
'''
patched = '''
\c[10]Prisoner\c[0]: Oh man, I just don't want to work too
close to this canyon...\. Do you have any idea how
deep it is?\. I don't know, but I do know that it's
deep enough to stay away from...
'''

[[dialogue]]
event = 27
page = 1
command = 4
original = '''
\c[10]Gefangener\c[0]: Diese Maulwurf-Dinger, die hier 
manchmal aus der Erde herausschwirren, können ganz 
schon nervig sein, nicht wahr?\. Aber ich kann dir 
ihren Schwachpunkt verraten.
'''
patched = '''
\c[10]Prisoner\c[0]: Those mole things that sometimes float
out of the ground here can be annoying, can't
they?\. But I can tell you their weak spot.
'''

[[dialogue]]
event = 27
page = 1
command = 8
original = '''
\c[10]Gefangener\c[0]: Interesse?\. Für 15 Erz sag ich es dir.
'''
patched = '''
\c[10]Prisoner\c[0]: Interested?\. I'll tell you for 15 ore.
'''

[[dialogue]]
event = 27
page = 1
command = 13
original = '''
\c[10]Gefangener\c[0]: Hey, ihr habt das Erz ja gar nicht!\.
So geht das nicht.
'''
patched = '''
\c[10]Prisoner\c[0]: Hey, you don't have the ore at all!\.
That won't do.
'''

[[dialogue]]
event = 27
page = 1
command = 26
original = '''
\c[10]Gefangener\c[0]: Hehe, danke sehr.\.
Dann hört mal gut zu.
'''
patched = '''
\c[10]Prisoner\c[0]: Hehe, thank you very much.\. So listen
carefully.
'''

[[dialogue]]
event = 27
page = 1
command = 28
original = '''
\c[10]Gefangener\c[0]: Ihre Stärke ist ihre \c[11]harte Schale\c[0].\. 
Durch sie kommt kaum ein Treffer, sei es mit der 
Waffe oder einem Zauber.\. Aber der Schutz kann 
gebrochen werden!
'''
patched = '''
\c[10]Prisoner\c[0]: Their strength is their \c[11]hard shell\c[0].\.
Hardly a hit breaks through it, be it with a
weapon or a spell.\. But that shield can be broken!
'''

[[dialogue]]
event = 27
page = 1
command = 32
original = '''
\c[10]Gefangener\c[0]: Anscheinend reagiert ihre Schale 
äußerst \c[11]empfindlich auf starken Lichteinfall\c[0]. 
'''
patched = '''
\c[10]Prisoner\c[0]: Apparently, their shield is \c[11]extremely
sensitive to strong light\c[0].
'''

[[dialogue]]
event = 27
page = 1
command = 34
original = '''
\c[10]Gefangener\c[0]: Also einfach einen Lichtzauber oder 
eine Lichtsare drauf pfeffern und das Ding steht 
dir schutzlos gegenüber!
'''
patched = '''
\c[10]Prisoner\c[0]: So just use some light magic or imbue
light into your weapon and it'll be defenseless!
'''

[[dialogue]]
event = 27
page = 1
command = 37
original = '''
\c[10]Gefangener\c[0]: Danke fürs Geschäft!
'''
patched = '''
\c[10]Prisoner\c[0]: Thanks for the deal!
'''

[[dialogue]]
event = 27
page = 1
command = 42
original = '''
\c[10]Gefangener\c[0]: Nein? Weißt du es bereits?\. Tja, 
dann muss ich mir das Erz wohl selber erarbeiten.
'''
patched = '''
\c[10]Prisoner\c[0]: No?\. Do you already know?\. Well, then I'll
have to work for the ore myself.
'''

[[dialogue]]
event = 28
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 29
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 30
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 32
page = 1
command = 2
original = '''
\c[10]Wache\c[0]: Ziemlich tiefer Abgrund oder?\. Solltet ihr 
zu lange zu schlecht Arbeit für uns leisten, kann 
es passieren, dass wir euch eines Tages einfach 
dort rein schmeißen.
'''
patched = '''
\c[10]Guard\c[0]: Pretty deep abyss, right?\. If you work
poorly for us too long, we might just end up
throwing you in there one day.
'''

[[dialogue]]
event = 32
page = 1
command = 6
original = '''
\c[10]Wache\c[0]: Wir müssen ja schließlich ökonomisch 
denken.\. Wäre doch eine Verschwendung, so schlechte 
Arbeitkräfte durchzufüttern.
'''
patched = '''
\c[10]Guard\c[0]: After all, we have to think economically.\.
It'd be quite a waste to feed such bad workers.
'''

[[dialogue]]
event = 32
page = 1
command = 9
original = '''
\c[10]Wache\c[0]: Also macht ja gute Arbeit, es sei denn ihr 
wollt unbedingt erfahren, was sich da unten in der 
Schlucht befindet.
'''
patched = '''
\c[10]Guard\c[0]: So do a good job, unless you really want to
find out what's down there.
'''

[[text]]
event = 27
page = 1
command = 9
original = '''Ja, das interessiert mich jetzt./Nein, danke.'''
patched = '''Yes, that'd be interesting./No thanks.'''

[[text]]
event = 27
page = 1
command = 10
original = '''Ja, das interessiert mich jetzt.'''
patched = '''Yes, that'd be interesting.'''

[[text]]
event = 27
page = 1
command = 41
original = '''Nein, danke.'''
patched = '''No thanks.'''
