[[dialogue]]
event = 35
page = 2
command = 24
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: So, ab hier wird es steiler. Wir 
befinden uns am Fuße des 
Torasgebirges.
'''
patched = '''
\c[13]\n[3]\c[0]: Alright, it only gets steeper
from here. We're at the base
of Mount Toras.
'''

[[dialogue]]
event = 35
page = 2
command = 28
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Ziemlich windig hier. 
'''
patched = '''
\c[2]\n[2]\c[0]: Pretty windy here.
'''

[[dialogue]]
event = 35
page = 2
command = 30
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Wir sollten versuchen, noch 
vor Einbruch der Nacht unseren Weg 
durch das Gebirge zu bahnen. 
'''
patched = '''
\c[13]\n[3]\c[0]: We should try to make our way
through the mountains before
nightfall.
'''

[[dialogue]]
event = 35
page = 2
command = 33
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Östlich vom Torasgebirge geht 
es dann weiter durch den Corine-
Wald...\. oder besser gesagt durch das 
Corine-Plateau.
'''
patched = '''
\c[13]\n[3]\c[0]: To the east of Mount Toras,
we'll continue through the
Corine Forest...\. or rather
the Corine Plateau.
'''

[[dialogue]]
event = 35
page = 2
command = 38
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Und jenseits dieser Gegend ist 
dann auch schon die Grenze zu 
Korzojeno. 
'''
patched = '''
\c[13]\n[3]\c[0]: And beyond that is the border
with Korzojeno.
'''

[[dialogue]]
event = 35
page = 2
command = 41
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Soweit so gut...\. Herr Kento,\. 
Herr Tirunel, ich hoffe sie sind mit 
der Anwendung von Signum-
Techniken bereits vertraut. 
'''
patched = '''
\c[13]\n[3]\c[0]: So far so good...\. Mr. Kento,\.
Mr. Tirunel,\. I hope you're already
familiar with the use of Signum
techniques.
'''

[[dialogue]]
event = 35
page = 2
command = 49
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Wir wissen lediglich wie man 
Signum-Techniken erlernt, aber 
nicht genau, was die Techniken an 
sich bringen.
'''
patched = '''
\c[1]\n[1]\c[0]: We only know how to learn
Signum techniques, but not exactly
what those techniques involve.
'''

[[dialogue]]
event = 35
page = 2
command = 54
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: So ist das...
'''
patched = '''
\c[13]\n[3]\c[0]: If that's how it is...
'''

[[dialogue]]
event = 35
page = 2
command = 56
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Nun, fast alle Signum-
Techniken die man lernt, sind einem 
bestimmten Element zugewiesen.
'''
patched = '''
\c[13]\n[3]\c[0]: So, almost all Signum
techniques you learn are
assigned to a certain element.
'''

[[dialogue]]
event = 35
page = 2
command = 59
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Dieses bedeutet, die Technik 
richtet entweder Schaden mit dem 
Attribut des Elementes an ...
'''
patched = '''
\c[13]\n[3]\c[0]: This means that these techs
either do damage with the
attribute of the element...
'''

[[dialogue]]
event = 35
page = 2
command = 62
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: ... oder sie bewirkt Element-
Typische Nebeneffekte.
'''
patched = '''
\c[13]\n[3]\c[0]: ...or it causes elemental side
effects.
'''

[[dialogue]]
event = 35
page = 2
command = 64
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Welche Nebeneffekte zu 
welchem Element gehören, werden 
Sie schon früh genug herausfinden.
'''
patched = '''
\c[13]\n[3]\c[0]: You'll find out which side
effects belong to which element
soon enough.
'''

[[dialogue]]
event = 35
page = 2
command = 68
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Nun zu der richtigen 
Anwendung der Techniken.
'''
patched = '''
\c[13]\n[3]\c[0]: Now for how to correctly apply
these techniques.
'''

[[dialogue]]
event = 35
page = 2
command = 70
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Wenn Sie im Kampf überlegt 
Signum-Techniken anwenden, ist der 
Gegner in der Regel weitaus 
schneller besiegt.
'''
patched = '''
\c[13]\n[3]\c[0]: If you use Signum techniques
deliberately in combat, the opponent
is usually defeated much faster.
'''

[[dialogue]]
event = 35
page = 2
command = 74
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Sie sollten wissen, dass die 
meisten Gegnern ihre Stärken und 
Schwächen haben, die man 
ausnutzen sollte.
'''
patched = '''
\c[13]\n[3]\c[0]: You should know that most
opponents have their strengths and
weaknesses that should be exploited.
'''

[[dialogue]]
event = 35
page = 2
command = 78
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Offensichtliche Stärken und 
Schwächen bemerkt man meistens 
schon bei der Abwehr.
'''
patched = '''
\c[13]\n[3]\c[0]: Obvious strengths and
weaknesses can usually be
seen in defense.
'''

[[dialogue]]
event = 35
page = 2
command = 81
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Einige Monster sind z.B. 
ziemlich resistent gegen physische 
Angriffe, können  aber empfindlich 
gegen Magie-Schaden sein.
'''
patched = '''
\c[13]\n[3]\c[0]: Some monsters are fairly
resistant to physical attacks,
but can be sensitive to magic
damage.
'''

[[dialogue]]
event = 35
page = 2
command = 85
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Dann können Gegner auch 
noch gegen ein bestimmtes Element 
immun bis empfindlich sein. 
'''
patched = '''
\c[13]\n[3]\c[0]: Then opponents can also be
immune to a certain element.
'''

[[dialogue]]
event = 35
page = 2
command = 88
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Grünschleime zum Beispiel 
sind sehr empfindlich gegen Wasser-
Angriffe, absorbieren aber jede 
Feuerattacke
'''
patched = '''
\c[13]\n[3]\c[0]: Green slimes, for example, are
very sensitive to water attacks, but
they absorb every fire attack.
'''

[[dialogue]]
event = 35
page = 2
command = 92
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Zudem können Gegner gegen 
bestimmte "Zustände" empfindlich 
sein. 
'''
patched = '''
\c[13]\n[3]\c[0]: In addition, opponents can be
sensitive to certain "conditions".
'''

[[dialogue]]
event = 35
page = 2
command = 95
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: So lassen sich Grünschleime 
zum Beispiel sehr leicht 
einschläfern. Sie sind empfindlich 
gegen "Schlaf"
'''
patched = '''
\c[13]\n[3]\c[0]: For example, green slimes can
be put to sleep very easily. They
are sensitive to "sleep".
'''

[[dialogue]]
event = 35
page = 2
command = 100
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Kennen Sie die Stärken und 
Schwächen der Gegner, fällt die 
Wahl der richtigen Technik nicht 
schwer.
'''
patched = '''
\c[13]\n[3]\c[0]: If you know the strengths and
weaknesses of your opponents,
choosing the right technique
is not difficult.
'''

[[dialogue]]
event = 35
page = 2
command = 104
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Bis man aber die Stärken und 
Schwächen kennt, muss man erstmal 
etwas ausprobieren.
'''
patched = '''
\c[13]\n[3]\c[0]: Until you know the strengths
and weaknesses, you have to try
something first.
'''

[[dialogue]]
event = 35
page = 2
command = 107
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Oder man hat ein paar 
"Magische Lupen" dabei. Wenn man 
sie verwendet, zeigen sie die Stärken 
und Schwächen eines Gegners an.
'''
patched = '''
\c[13]\n[3]\c[0]: Or if you have some "magic
lens" with you. When used, they
show an opponent's strengths
and weaknesses.
'''

[[dialogue]]
event = 35
page = 2
command = 111
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Damit Sie aber auch auf die 
verschiedensten Schwachpunkt eine 
passende Technik haben...
'''
patched = '''
\c[13]\n[3]\c[0]: So that you have the right
technique for a wide range of
weak points...
'''

[[dialogue]]
event = 35
page = 2
command = 114
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: ...sollten Sie sich nicht zu 
sehr auf ein Element konzentrieren. 
Stufen sie am besten verschiedene 
Element-Level gleichzeitig auf.
'''
patched = '''
\c[13]\n[3]\c[0]: ...you shouldn't concentrate
too much on one element. It's best
to level up different element
levels at the same time.
'''

[[dialogue]]
event = 35
page = 2
command = 118
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Mehr gibt es dazu ansonsten 
nicht zu sagen.
'''
patched = '''
\c[13]\n[3]\c[0]: There isn't much else to say
about it.
'''

[[dialogue]]
event = 35
page = 2
command = 124
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Meine Güte, du weißt ja 
ziemlich gut bescheit, Soko, äh, ich 
meine Frau Filaja.
'''
patched = '''
\c[2]\n[2]\c[0]: Gosh, you must be pretty
clever huh, Soko, uh, I mean
Ms. Filaja.
'''

[[dialogue]]
event = 35
page = 2
command = 128
has_portrait = true
character = '''Cibon'''
original = '''
(\c[2]\n[2]\c[0]: Oh mein Gott. Ein weiblicher 
"Vorento" als Reisegefährte... Das 
kann ja heiter werden...) 
'''
patched = '''
(\c[2]\n[2]\c[0]: Oh god. A female "Vorento"
travelling with us... This'll be
so much fun...)
'''

[[dialogue]]
event = 35
page = 2
command = 132
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Dieses Wissen gehört 
eigentlich zu der Ausbildung von 
Soldaten unseresgleichen. 
'''
patched = '''
\c[13]\n[3]\c[0]: This knowledge was actually
part of the our type of training.
'''

[[dialogue]]
event = 35
page = 2
command = 136
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Sie sollten wissen, dass wir 
erst vor kurzem, um genau zu sein 
Gestern, in dieses Thema eingeweiht 
wurden.
'''
patched = '''
\c[1]\n[1]\c[0]: You should know that we were
only recently introduced to this
topic, precisely yesterday.
'''

[[dialogue]]
event = 35
page = 2
command = 141
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Achso...\.
Na ja, wenn das so ist.
'''
patched = '''
\c[13]\n[3]\c[0]: Oh...\. Well, if that's the
case.
'''

[[dialogue]]
event = 35
page = 2
command = 146
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: In Ordnung.
'''
patched = '''
\c[13]\n[3]\c[0]: Alright.
'''

[[dialogue]]
event = 35
page = 2
command = 154
has_portrait = true
original = '''
\c[10]Herr Uroto\c[0]: Wir sollten endlich 
losgehen.\. Wir wollen das Gebirge ja 
noch heute durchqueren... 
'''
patched = '''
\c[10]Mr. Uroto\c[0]: We should get going.\. We
still want to cross the mountains
today...
'''

[[dialogue]]
event = 35
page = 2
command = 158
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Zu Befehl, Herr Uroto.
'''
patched = '''
\c[13]\n[3]\c[0]: At your command, Mr. Uroto.
'''

[[dialogue]]
event = 35
page = 2
command = 167
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Tsk, sie tut so, als ob sie 
unsere Anführerin wäre!\. Legt 
einfach fest, wie wir vorgehen.\. 
Sie gibt uns regelrecht Anweisungen!
'''
patched = '''
\c[2]\n[2]\c[0]: Tsk, she pretends to be our
leader!\. Keeping track of our every
move.\. She downright orders us
around!
'''

[[dialogue]]
event = 35
page = 2
command = 172
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Wenn du was dagegen hast, 
wieso widersprichst du ihr nicht?
'''
patched = '''
\c[1]\n[1]\c[0]: If you have a problem, why
don't you tell her?
'''

[[dialogue]]
event = 35
page = 2
command = 175
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Bisher hab ich ja nichts gegen 
ihre Anweisungen einzuwenden...
Aber diese Art gefällt mir ganz und
gar nich', Kumpel.
'''
patched = '''
\c[2]\n[2]\c[0]: So far, I haven't had any
problems with your instructions...
But I don't like that kind of
thing in general.
'''

[[dialogue]]
event = 35
page = 2
command = 180
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Es kann nie schaden, wenn 
wir eine Person im Team haben, die 
uns leitet...\. Sie scheint ja recht 
motiviert an die Sache ran zu gehen.
'''
patched = '''
\c[1]\n[1]\c[0]: It couldn't hurt if we have
a person in the team who's leading
us...\. She seems to be very
motivated to do it.
'''

[[dialogue]]
event = 35
page = 2
command = 185
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Sie siezt uns, sie gibt uns 
Anweisungen!\. Das ist, als ob man mit 
einem Ausbilder den Auftrag 
erledigt.
'''
patched = '''
\c[2]\n[2]\c[0]: The way she addresses us, the
way she bosses us around!\. It's like
doing an assignment with an
instructor.
'''

[[dialogue]]
event = 35
page = 2
command = 197
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: \s[5]Hallo?\.\s[0] Wo bleiben Sie denn?\. 
Trödeln Sie bitte nicht rum, ja?
'''
patched = '''
\c[13]\n[3]\c[0]: \s[5]Hello?\.\s[0] Are you coming with us
or not?\. Please don't loiter around,
okay?
'''

[[dialogue]]
event = 35
page = 2
command = 207
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Hmpf....
'''
patched = '''
\c[2]\n[2]\c[0]: Hmph...
'''

[[dialogue]]
event = 35
page = 2
command = 209
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Komm lass uns gehen, Cibon.\. 
Das können wir nachher weiter 
diskutieren...
'''
patched = '''
\c[1]\n[1]\c[0]: Let's go, Cibon.\. We can
discuss this later...
'''

[[text]]
event = 35
page = 2
command = 46
has_portrait = true
original = '''Ehrlich gesagt... Nein/Ja wir wissen bescheit.'''
patched = '''Honestly... Not really./Yeah, we already know.'''

[[text]]
event = 35
page = 2
command = 47
has_portrait = true
original = '''Ehrlich gesagt... Nein'''
patched = '''Honestly... Not really.'''

[[text]]
event = 35
page = 2
command = 144
has_portrait = true
original = '''Ja wir wissen bescheit.'''
patched = '''Yeah, we already know.'''
