[[dialogue]]
event = 35
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Ich kann diese ganzen Jammerlappen 
nicht verstehen.\. Die sollten froh sein, dass sie 
etwas tun können.\. Und wenn es Minenarbeit ist.
'''
patched = '''
\c[10]Prisoner\c[0]: I can't understand all these people
whining.\. They should be happy that they can at
least do something.\. And it's working in the
mine at that.
'''

[[dialogue]]
event = 35
page = 1
command = 5
original = '''
\c[10]Gefangener\c[0]: Nichts ist schlimmer, als Wochen bis 
Monate lang einsam und tatenlos in einer Zelle zu 
sitzen.\. Glaubt mir, ich spreche aus Erfahrung.
'''
patched = '''
\c[10]Prisoner\c[0]: Nothing is worse than sitting idly by
and waiting alone in a cell for weeks or months.\.
Trust me, I speak from experience.
'''

[[dialogue]]
event = 35
page = 1
command = 11
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Hm...\. da könnte er wirklich 
Recht haben. 
'''
patched = '''
\c[2]\n[2]\c[0]: Hm...\. He could be onto
something.
'''

[[dialogue]]
event = 35
page = 1
command = 14
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Dieses permanente Rumgesitze 
in der Zelle dieser anderen Truppe 
hätt' mich auf Dauer in den Wahnsinn 
getrieben. 
'''
patched = '''
\c[2]\n[2]\c[0]: Just sitting around like that
for who knows how long would've
driven me crazy by now!
'''

[[dialogue]]
event = 35
page = 1
command = 20
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Aber wenigstens konnte man 
dort ausschlafen.
'''
patched = '''
\c[13]\n[3]\c[0]: But at least you'd be able to
actually sleep.
'''

[[dialogue]]
event = 35
page = 1
command = 23
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Ja, genau.
'''
patched = '''
\c[1]\n[1]\c[0]: Yeah, exactly.
'''

[[dialogue]]
event = 35
page = 1
command = 25
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: ...\. Ich hätte nie gedacht, so 
etwas von DIR zu hören, Soko.
'''
patched = '''
\c[2]\n[2]\c[0]: I never thought I'd hear
something like that from YOU of
all people, Soko.
'''

[[dialogue]]
event = 35
page = 1
command = 29
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: ...
'''
patched = '''
\c[1]\n[1]\c[0]: ...
'''

[[dialogue]]
event = 36
page = 1
command = 2
original = '''
\c[10]Gefangene\c[0]: Vor einer Woche oder zwei war dieser 
Bereich noch voller reicher Erzreserven, die 
leicht erreichbar waren. 
'''
patched = '''
\c[10]Prisoner\c[0]: A week or two ago, this area was still
full of rich ore reserves that were easily
accessible.
'''

[[dialogue]]
event = 36
page = 1
command = 5
original = '''
\c[10]Gefangene\c[0]: Aber seit wir hier letztens ein 
kleines Erdbeben hatten, ist das meiste mit 
Gestein überschüttet und nur noch schwer zu 
erreichen.
'''
patched = '''
\c[10]Prisoner\c[0]: But ever since we had that recent
earthquake here, most of it has been showered
with rocks and is too difficult to reach.
'''

[[dialogue]]
event = 37
page = 1
command = 11
original = '''
\c[10]Pauamainer-Miglied\c[0]: Unglaublich, du hast es 
tatsächlich durch das Steingerümpel da unten 
geschafft.\. Dafür kriegste nen Ordnen!\. Weiter so, 
Kumpel!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Unbelievable, you actually made
it through the stone debris down there.\. You'll get
a medallion for that!\. Keep it up!
'''

[[dialogue]]
event = 37
page = 1
command = 26
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ihr guckt so verdutzt.\. Wenn 
ihr mehr über uns und die Minen-Orden 
erfahren wollt, besucht einfach unseren 
Stützpunkt.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: You look so confused.\. If you
want to learn more about us and the miner
medallions, just visit our base.
'''

[[dialogue]]
event = 37
page = 1
command = 30
original = '''
\c[10]Pauamainer-Miglied\c[0]: Dieser befindet sich im 
mittleren Bereich der Mine.\. Fahrt beim nächsten 
Mal mit der Lore einfach rechts und dann 
geradeaus.
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It's located at the center of
the mine.\. Next time on the railways, just go
right and then straight.
'''

[[dialogue]]
event = 37
page = 1
command = 36
original = '''
\c[10]Pauamainer-Miglied\c[0]: Glück auf!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: Good luck!
'''

[[dialogue]]
event = 37
page = 1
command = 43
original = '''
\c[10]Pauamainer-Miglied\c[0]: Ist immer witzig, die 
verdutzten Blicke der Leute auf der anderen Seite 
zu sehen, nicht wahr?\. Ja-ha!\. Das ist Minenarbeit, 
wie sie sein sollte!
'''
patched = '''
\c[10]Pauamainer Member\c[0]: It's always funny to see
people's puzzled looks on the other side, isn't
it?\. Yeah!\. This is mining as it should be!
'''

[[dialogue]]
event = 39
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 40
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 41
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 42
page = 1
command = 3
original = '''
\c[10]Wache\c[0]: Hey, ihr habt es echt da durch geschafft, 
nicht schlecht, nicht schlecht.\. War bestimmt 
ordentlich Erz da drüben, oder?
'''
patched = '''
\c[10]Guard\c[0]: Hey, you actually made it through, not bad
I'll give you that.\. It was the ore over there,
wasn't it?
'''

[[dialogue]]
event = 42
page = 1
command = 8
original = '''
\c[10]Wache\c[0]: Hm...\. interessant, interessant. \.Ich frage 
mich, wie man da unten durch kommt, bei all dem 
Gestein. \.Einer hat es ja anscheinend geschafft.
'''
patched = '''
\c[10]Guard\c[0]: Hm...\. Interesting, interesting.\. I wondered
how one would get over there with all the rocks
around.\. Apparently someone did it.
'''
