[[dialogue]]
event = 4
page = 1
command = 2
original = '''
\c[10]Verkäuferin\c[0]: Wir führen Waffen und Rüstungen 
aus stabiler Bronze. 
'''
patched = '''
\c[10]Saleswoman\c[0]: We carry weapons and armor made
from the finest bronze!
'''

[[dialogue]]
event = 5
page = 1
command = 2
original = '''
\c[10]Soldat des Briganten-Ordens\c[0]: Ach, ihr beiden 
seid endlich wieder zurück?\. Wieso hat das so 
lange gedauert?
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Oh, you two are finally back?\.
What took so long?
'''

[[dialogue]]
event = 5
page = 1
command = 7
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Die Diebe haben uns keine 
Probleme gemacht, nur hat es leider 
ziemlich lange gedauert, bis sie sich 
überhaupt blicken ließen.
'''
patched = '''
\c[1]\n[1]\c[0]: The thieves didn't cause us
any problems, but unfortunately it
took quite a long time for them to
show up.
'''

[[dialogue]]
event = 5
page = 1
command = 12
original = '''
\c[10]Soldat des Briganten-Ordens\c[0]: Ach, wenn das so 
ist.\. Ich dachte schon, ihr hättet tatsächlich 
Probleme mit dieser kleinen Räuberbande 
gehabt.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Well, if that's what you
say.\. I thought you actually had problems
with this little band of robbers.
'''

[[dialogue]]
event = 5
page = 1
command = 16
original = '''
\c[10]Soldat des Briganten-Ordens\c[0]: Sir Vorento 
wartet jedenfalls schon gespannt auf eure 
Ankunft.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Sir Vorento is
looking forward to your arrival.
'''

[[dialogue]]
event = 5
page = 1
command = 19
original = '''
\c[10]Soldat des Briganten-Ordens\c[0]: Lasst ihn nicht zu 
lange warten. Ihr seid neu und müsst noch 
einen guten Eindruck hinterlassen. 
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Don't make him wait too long.
You are new here and still have to make
a good impression.
'''

[[dialogue]]
event = 6
page = 1
command = 2
original = '''
\c[10]Mann\c[0]: Hier im Norden schmelzen wir nur das 
beste Metall und haben so genau das richtige 
Material für robuste Waffen und Rüstungen.
'''
patched = '''
\c[10]Man\c[0]: Here in the north, we only melt the
best metal and have just the right
material for robust weapons and armor.
'''

[[dialogue]]
event = 6
page = 1
command = 5
original = '''
\c[10]Mann\c[0]: Waffen aus Brigantia sind bekannt für 
ihre hohe Qualität und Stabilität.
'''
patched = '''
\c[10]Man\c[0]: Weapons from Brigantia are known for
their high quality and durability.
'''

[[dialogue]]
event = 6
page = 1
command = 10
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Schön und gut, aber ich hab 
gehört, dass unsere Waffen einen 
ziemlich schlechten Schliff haben, im 
Vergleich zu denen im Ausland.
'''
patched = '''
\c[2]\n[2]\c[0]: Alright, but I've heard that our
weapons have a pretty bad polish
compared to those abroad.
'''

[[dialogue]]
event = 6
page = 1
command = 15
original = '''
\c[10]Mann\c[0]: Ähh...\. ja...\. 
Keine Ahnung.
'''
patched = '''
\c[10]Man\c[0]: Well...\. yes...\.
I don't know.
'''
