[[dialogue]]
event = 7
page = 1
command = 2
original = '''
\c[10]Alte Mann\c[0]: Soso, ihr seid also Soldaten aus 
Brigantia?\. Dürfte ich euch dann bitten schleunigst 
dieses Haus zu verlassen?\. Mit euch Leuten wollen 
wir NICHTS zu tun haben!
'''
patched = '''
\c[10]Old Man\c[0]: So, are you soldiers from Brigantia?\.
May I ask you to leave this house as soon as
possible?\. We don't want ANYTHING to do with
you rotten pieces of shit!
'''
