[[dialogue]]
event = 9
page = 2
command = 2
original = '''
\c[10]Alte Frau\c[0]: Unglaublich was für Sachen es alle zu 
kaufen gibt heutzutage...\. Früher gab es hier Brot, 
Gemüse wie Lokri-Knollen und etwas Fleisch. 
'''
patched = '''
\c[10]Old Woman\c[0]: Unbelievable how many things there are
to buy nowadays...\. In the past, all there was
were things like bread, vegetables like Lokri
potatoes, and some meat.
'''

[[dialogue]]
event = 9
page = 2
command = 5
original = '''
\c[10]Alte Frau\c[0]: Und heute bieten sie so merkwürdige 
Sachen wie "Heilsirub" an.\. Ich werde so ein Zeug 
niemals trinken, solange man mir nicht sagen kann, 
was da alles drin ist!
'''
patched = '''
\c[10]Old Woman\c[0]: But nowadays, they offer strange
things like "heal syrup".\. I'll never drink
that kind of stuff unless you can tell me
what's in there!
'''

[[dialogue]]
event = 9
page = 2
command = 15
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Nebenbei,\. wisst ihr 
eigentlich woraus das Zeug besteht?
'''
patched = '''
\c[2]\n[2]\c[0]: Speaking of which,\. do you
happen know what that stuff is
made of?
'''

[[dialogue]]
event = 9
page = 2
command = 18
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Heilsirubs?\. Hm...
'''
patched = '''
\c[1]\n[1]\c[0]: Heal syrup?\. Hm...
'''

[[dialogue]]
event = 9
page = 2
command = 20
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Irgendeine pflanzliche 
Substanz, versehen mit einer Signum-
Aura. 
'''
patched = '''
\c[13]\n[3]\c[0]: Any vegetable extract imbued
with a Signum aura.
'''

[[dialogue]]
event = 9
page = 2
command = 23
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Aus welchem Pflanzen genau die 
Substanz besteht, weiß ich nicht, 
aber es gibt mehr als eine Methode 
so etwas zuzubreiten.
'''
patched = '''
\c[13]\n[3]\c[0]: I don't know which plants it's
usually made of, but there's more
than one way to prepare something
like that.
'''

[[dialogue]]
event = 9
page = 2
command = 28
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: In den Dingern steckt also 
auch Signum?\. Unglaublich.
'''
patched = '''
\c[2]\n[2]\c[0]: So there's also Signum in it?\.
Wicked.
'''

[[dialogue]]
event = 10
page = 1
command = 2
original = '''
\c[10]Verkäuferin\c[0]: Benötigen Sie Heilmittel?\. Wir haben 
auch praktische Blendbomben im Angebot.
'''
patched = '''
\c[10]Saleswoman\c[0]: Do you need supplies?\. We also have
practical smoke bombs in stock.
'''

[[dialogue]]
event = 11
page = 1
command = 2
original = '''
\c[10]Verkäuferin\c[0]: Verkauft wird über die Theke.
'''
patched = '''
\c[10]Saleswoman\c[0]: We're only selling stuff over the
counter.
'''
