[[dialogue]]
event = 2
page = 1
command = 6
original = '''
\v[31]   ----  \v[41]
\v[32]   ----  \v[42]
\v[33]   ----  \v[43]
\v[34]   ----  \v[44]
'''
patched = '''
\v[31]   ----  \v[41]
\v[32]   ----  \v[42]
\v[33]   ----  \v[43]
\v[34]   ----  \v[44]
'''

[[dialogue]]
event = 2
page = 2
command = 78
original = '''
LEVEL UP
'''
patched = '''
LEVEL UP
'''

[[dialogue]]
event = 3
page = 1
command = 48
original = '''
Curia gelernt!
'''
patched = '''
Curia gelernt!
'''

[[dialogue]]
event = 5
page = 1
command = 1
original = '''
Status Werte:
'''
patched = '''
Status Werte:
'''

[[dialogue]]
event = 5
page = 1
command = 9
original = '''
MAX-HP: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
MAX-HP: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 5
page = 1
command = 20
original = '''
MAX-MP: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
MAX-MP: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 5
page = 1
command = 31
original = '''
ATTACK: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
ATTACK: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 5
page = 1
command = 42
original = '''
ABWEHR: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
ABWEHR: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 5
page = 1
command = 53
original = '''
MENTAL: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
MENTAL: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 5
page = 1
command = 64
original = '''
AGILITY: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''
patched = '''
AGILITY: Kento: \v[81]  
Cibon: \v[82]     Soko: \v[83]  
Genyu: \v[84]  Felcis: \v[85]
Ileya: \v[86]  Ileya: \v[87]
'''

[[dialogue]]
event = 7
page = 1
command = 1
original = '''
ik klau dir alle Items!!!1
'''
patched = '''
ik klau dir alle Items!!!1
'''

[[dialogue]]
event = 7
page = 1
command = 7
original = '''
ik geb dir alle Items wieder!!!1
'''
patched = '''
ik geb dir alle Items wieder!!!1
'''

[[dialogue]]
event = 12
page = 1
command = 0
original = '''
QUATSCHMODUS AKTIVIERT!!!1
'''
patched = '''
QUATSCHMODUS AKTIVIERT!!!1
'''

[[dialogue]]
event = 13
page = 1
command = 0
original = '''
IK MAKE DIR SCHADEN!
'''
patched = '''
IK MAKE DIR SCHADEN!
'''
