[[dialogue]]
event = 6
page = 1
command = 13
has_portrait = true
original = '''
\c[10]?????\c[0]: Nein, ich hab mich nicht 
verschaut.\. Er ist es.\. Glaubst du 
wirklich, ich würde dieses Gesicht 
vergessen?
'''
patched = '''
\c[10]?????\c[0]: No, I'm not mistaking him for
someone else.\. That's him over there!\.
Do you really think I'd ever forget
that face?
'''

[[dialogue]]
event = 6
page = 1
command = 17
has_portrait = true
original = '''
\c[10]?????\c[0]: Es ist der selbe General, der 
uns damals alles genommen hat.
'''
patched = '''
\c[10]?????\c[0]: It's the exact same general who
took everything away from us back
then.
'''

[[dialogue]]
event = 6
page = 1
command = 25
has_portrait = true
original = '''
\c[10]?????\c[0]: N-\.Nein...\. Bitte nicht hier...
'''
patched = '''
\c[10]?????\c[0]: N-\.No...\. Not like this...
'''

[[dialogue]]
event = 6
page = 1
command = 31
has_portrait = true
original = '''
\c[10]?????\c[0]: Genji...\. Niemand von uns hat 
diese Person vergessen, noch werden 
wir das jemals tun.
'''
patched = '''
\c[10]?????\c[0]: Genji...\. None of us have
forgotten this person, nor will
we ever forget what he did to us.
'''

[[dialogue]]
event = 6
page = 1
command = 34
has_portrait = true
original = '''
\c[10]?????\c[0]: Wir dürfen uns aber in dieser 
Situation nicht von Rachegedanken 
leiten lassen, verstehst du das?\.
Wir haben eine Mission...
'''
patched = '''
\c[10]?????\c[0]: But in this situation, we can't
let ourselves be guided by thoughts of
revenge, understand?\. We have a
mission...
'''

[[dialogue]]
event = 6
page = 1
command = 41
has_portrait = true
original = '''
\c[10]Genji\c[0]: Mir geht es nicht um Rache.\.
Mir geht es hier um die Gefahr, die 
diese Person darstellt.
'''
patched = '''
\c[10]Genji\c[0]: I'm not concerned about
revenge.\. I'm concerned about
the danger this person poses.
'''

[[dialogue]]
event = 6
page = 1
command = 44
has_portrait = true
original = '''
\c[10]Genji\c[0]: Sollte die Flucht die du 
prophezeist stattfinden und Kento 
dabei auf diese Person stoßen \.- was 
dann?
'''
patched = '''
\c[10]Genji\c[0]: Should the escape in the
prophecy take place and Kento were
to encounter this person,\. what then?
'''

[[dialogue]]
event = 6
page = 1
command = 48
has_portrait = true
original = '''
\c[10]Genji\c[0]: Wir beide wissen, wozu dieser 
General fähig ist.\. Zwillingsseele 
hin oder her, Kento würde das nicht 
überstehen!
'''
patched = '''
\c[10]Genji\c[0]: We both know what this general
is capable of.\. Twin soul or not,
Kento will not survive!
'''

[[dialogue]]
event = 6
page = 1
command = 52
has_portrait = true
original = '''
\c[10]Genji\c[0]: Du kannst mir nicht erzählen, 
dass Heimdall diese Tatsache 
komplett entgangen ist!
'''
patched = '''
\c[10]Genji\c[0]: You can't tell me that Heimdall
completely missed this fact!
'''

[[dialogue]]
event = 6
page = 1
command = 61
has_portrait = true
original = '''
\c[10]?????\c[0]: ...er hat mich gewarnt.  \.
Dennoch, ist es keine Situation in 
der wir vorzeitig eingreifen 
sollten.
'''
patched = '''
\c[10]?????\c[0]: He warned me.\. Nevertheless, it
isn't a situation we should intervene
in prematurely.
'''

[[dialogue]]
event = 6
page = 1
command = 68
has_portrait = true
original = '''
\c[10]Genji\c[0]: Und deswegen sagst du uns 
nichts?\. Dies ist keine Situation, 
die wir durch spontanes Eingreifen 
geregelt bekommen können!
'''
patched = '''
\c[10]Genji\c[0]: And that's why you didn't tell
us anything?\. This isn't a situation
that we can save at the last minute!
'''

[[dialogue]]
event = 6
page = 1
command = 73
has_portrait = true
original = '''
\c[10]Genji\c[0]: Wenn wir unüberlegt da rein 
stürzen kostet das nicht nur Kentos 
Leben, sondern unsers gleich dazu.\.
Willst du das verantworten?
'''
patched = '''
\c[10]Genji\c[0]: If we have to rush into it
without thinking, it not only costs
Kento's life, but also ours.\. Do you
want to be responsible for that?
'''

[[dialogue]]
event = 6
page = 1
command = 81
has_portrait = true
original = '''
\c[10]Genji\c[0]: Wir müssen uns vorbereiten. 
Das ist alles was ich damit sagen 
will.
'''
patched = '''
\c[10]Genji\c[0]: We have to prepare. That's all
I can say about it.
'''

[[dialogue]]
event = 6
page = 1
command = 91
has_portrait = true
original = '''
\c[10]?????\c[0]: Du hast recht.\. Ich habe diese 
Tatsache wohl unterschätzt...
'''
patched = '''
\c[10]?????\c[0]: You're right.\. I probably did
underestimate this fact...
'''

[[dialogue]]
event = 6
page = 1
command = 99
has_portrait = true
original = '''
\c[10]?????\c[0]: Kumiko?\. Macht dich bitte mit 
der Gegend vertraut.\. Wir werden 
deine Fähigkeiten womöglich in 
Anspruch nehmen müssen.
'''
patched = '''
\c[10]?????\c[0]: Kumiko?\. Please survey the area
and get familiar with it.\. We may need
your skills after all.
'''

[[dialogue]]
event = 6
page = 1
command = 104
has_portrait = true
original = '''
\c[10]Kumiko\c[0]: G-\.Geht in Ordnung!
'''
patched = '''
\c[10]Kumiko\c[0]: O-\.Okay!
'''
