[[dialogue]]
event = 4
page = 2
command = 2
original = '''
\c[10]Frau\c[0]: Hm hm, was koch ich heute?\. So viele neue 
Zutaten die man heutzutage kaufen kann!\. Da macht 
das Kochen wieder so richtig Spaß!
'''
patched = '''
\c[10]Woman\c[0]: Hm hm, what shall I cook today?\. So many
new ingredients to buy these days!\. Cooking is
getting really fun again!
'''

[[dialogue]]
event = 5
page = 1
command = 3
original = '''
\c[10]Junge\c[0]: Bitte!\. Jemand muss meine Mutter stoppen!\.
Seit die Händler hier neuartige Zutaten von sonst 
woher anbieten, kommt sie auf die verrücktesten 
Ideen was Gerichte angeht!
'''
patched = '''
\c[10]Boy\c[0]: You gotta help me!\. Someone has to stop my
mom!\. Ever since those merchants started offering
new ingredients from other places, she's had the
craziest ideas about what to cook!
'''

[[dialogue]]
event = 5
page = 1
command = 7
original = '''
\c[10]Junge\c[0]: Und wir sind ihre Versuchskaninchen!\. Wir 
dürfen die Ergebnisse all dieser Experimente 
essen.\. Sehr lange überleben wir das nicht mehr!
'''
patched = '''
\c[10]Boy\c[0]: And we're her guinea pigs!\. We're still
allowed to eat the results of all these
experiments.\. We won't survive for very long!
'''

[[dialogue]]
event = 5
page = 1
command = 13
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Na komm, so schlimm kann es 
nun doch wirklich nicht sein.
'''
patched = '''
\c[13]\n[3]\c[0]: I'm sure it can't be that bad.
'''

[[dialogue]]
event = 5
page = 1
command = 16
original = '''
\c[10]Junge\c[0]: Ach ja?\. Was ist mit\s[4] "Sardinen in 
Blauperlen-Pfeffer-Marinade mit Reps-Lokri-
Knollen-Püree, Bier-Flajo-Frucht-Soße und Plotio-
Strauch-Salat"?
'''
patched = '''
\c[10]Boy\c[0]: Oh really?\. What about\s[4] "sardines in blue
pearls and pepper marinade with a side of
sunbread and Lokri potatoes puree, beer and
flajo fruit sauce, and plotio shrub salad"?
'''

[[dialogue]]
event = 5
page = 1
command = 22
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Du meine Güte...
'''
patched = '''
\c[1]\n[1]\c[0]: Goodness...
'''

[[dialogue]]
event = 5
page = 1
command = 25
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Wurde das heimische Bier 
verwendet?
'''
patched = '''
\c[2]\n[2]\c[0]: Please don't tell me she used
the beer around here...
'''

[[dialogue]]
event = 5
page = 1
command = 28
original = '''
\c[10]Junge\c[0]: Joa...
'''
patched = '''
\c[10]Boy\c[0]: She did...
'''

[[dialogue]]
event = 5
page = 1
command = 31
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Mein TIEFSTES Beileid, Junge.
'''
patched = '''
\c[2]\n[2]\c[0]: My DEEPEST condolences, kid.
'''

[[dialogue]]
event = 5
page = 1
command = 35
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Plotio...\. Strauch...\. Salat...
'''
patched = '''
\c[13]\n[3]\c[0]: Plotio...\. shrub...\. salad...
'''
