[[dialogue]]
event = 2
page = 1
command = 2
original = '''
Dies ist ein Test!
'''
patched = '''
Dies ist ein Test!
'''

[[dialogue]]
event = 2
page = 1
command = 5
has_portrait = true
character = '''Kento'''
original = '''
\c[2]\n[1]:\c[0] Aha...........
'''
patched = '''
\c[2]\n[1]:\c[0] Aha...........
'''

[[dialogue]]
event = 2
page = 1
command = 8
original = '''
......WAS?!
'''
patched = '''
......WAS?!
'''

[[dialogue]]
event = 3
page = 1
command = 1
original = '''
Dies ist ein Test!
'''
patched = '''
Dies ist ein Test!
'''
