[[dialogue]]
event = 7
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Verflucht!\. Zurzeit 
gibt es kaum Aufträge für den Briganten-Orden.\. 
Die meiste Zeit haben wir nichts zu tun und 
sitzen hier einfach nur rum...
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Damn!\. At the moment, there
are hardly any orders from the Brigantine Order.\.
Most of the time, we have nothing to do and
just sit here...
'''

[[dialogue]]
event = 8
page = 1
command = 3
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: *seufz*\. Das Spiel 
liegt mir nicht...
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: *sigh*\. I don't like
this game...
'''

[[dialogue]]
event = 9
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Verdammt, du 
hast eine totale Glückssträhne! 
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Damn, you had a
total streak of luck!
'''

[[dialogue]]
event = 10
page = 1
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: \s[4]Full House!\.
\s[0]Und wieder gewonnen! 
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: \s[4]Full House!\.
\s[0]And I win again!
'''

[[dialogue]]
event = 11
page = 2
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Hm... eigentlich 
ganz interessant, was man hier für Bücher 
findet. Man erfährt viel über die Geschichte 
dieses Landes.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Hm... the books you can
find here are actually quite interesting.
You learn a lot about the history of this country.
'''

[[dialogue]]
event = 11
page = 2
command = 6
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Wusstet ihr, dass 
früher, als noch ein König an der Macht war, 
das Schloss von Nomerea sein Stützpunkt und 
das Zentrum des Landes war?
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Did you know that when the
king was in power, Nomerea Castle was his base
and the center of the country?
'''

[[dialogue]]
event = 11
page = 2
command = 10
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Erst seit die 
Regierung in Buronia liegt, dient das Schloss 
nur zur Ausbildung von Soldaten.
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: The castle only started
being used to train soldiers ever since the
government moved to Buronia.
'''

[[dialogue]]
event = 12
page = 2
command = 2
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Ohje, ich weiß nicht, 
wie ich die Zeit totschlagen soll...
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Oh man, I don't know how to
pass the time...
'''

[[dialogue]]
event = 12
page = 2
command = 7
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Hm...\. Wie wäre es mit 
trainieren?
'''
patched = '''
\c[1]\n[1]\c[0]: Hm...\. how about training?
'''

[[dialogue]]
event = 12
page = 2
command = 10
original = '''
\c[10]Soldat vom Briganten-Orden\c[0]: Trainieren?\. 
...\. Öh?
'''
patched = '''
\c[10]Brigantian Soldier\c[0]: Training?\. Huh?
'''

[[dialogue]]
event = 12
page = 2
command = 14
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Ach Kumpel,\. nicht jeder is' so 
trainingsbesessen wie du.\. Das 
musste verstehen.
'''
patched = '''
\c[2]\n[2]\c[0]: Kento,\. not everyone is as
obsessed with training as you are.\.
You gotta understand.
'''

[[dialogue]]
event = 12
page = 2
command = 18
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: "Trainingsbesessen"?
'''
patched = '''
\c[1]\n[1]\c[0]: "Obsessed with training"?
'''

[[dialogue]]
event = 12
page = 2
command = 20
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Wenn du in deiner Freizeit 
nichts Besseres zu tun hast,\. als mit 
der Waffe zu üben,\. bist du das,\. 
finde ich.
'''
patched = '''
\c[2]\n[2]\c[0]: If you had nothing better to
do in your free time,\. I'd find you\.
just practicing with your weapon\.
all day.
'''

[[dialogue]]
event = 12
page = 2
command = 25
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Öhm... Wenn man als Soldat 
was werden will muss man doch viel 
trainieren.\. 
Also was ist daran falsch? 
'''
patched = '''
\c[1]\n[1]\c[0]: Well... If you want to become
a soldier, you have to train a lot.\.
So what's wrong with that?
'''

[[dialogue]]
event = 12
page = 2
command = 30
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Ohje...\. vergessen wir das 
besser.\. Du wirst es nicht verstehen.
'''
patched = '''
\c[2]\n[2]\c[0]: Oh...\. let's just forget about
that.\. You wouldn't understand.
'''
