[[dialogue]]
event = 9
page = 1
command = 3
original = '''
\c[10]Postboten-Neuling\c[0]: Jetzt waren wir schon in Sinun, 
Helnovien und Gencorin und in jeder Post-
Versandstelle mussten wir uns im Lager-Raum 
aufhalten um Pause zu machen.
'''
patched = '''
\c[10]Rookie Postman\c[0]: Now we've already been in Sinun,
Helnovien, and Gencorin, and in every post
office, we had to be in the storage room
to take a break.
'''

[[dialogue]]
event = 9
page = 1
command = 7
original = '''
\c[10]Postboten-Neuling\c[0]: Gibt es überhaupt eine 
Postversandstelle wo wir uns nicht zwischen 
Briefen und Paketen setzen müssen, um 
uns auszuruhen?
'''
patched = '''
\c[10]Rookie Postman\c[0]: Is there any post office at all
where we don't have to sit between letters and
parcels to rest?
'''

[[dialogue]]
event = 9
page = 1
command = 14
original = '''
\c[10]Postboten\c[0]: Jupp,\. bei der Postversandstelle an 
Hamsol,\. südlich von hier.
'''
patched = '''
\c[10]Postman\c[0]: Yep,\. the post office at Hamsol,\. south
of here.
'''

[[dialogue]]
event = 9
page = 1
command = 17
original = '''
\c[10]Postboten-Neuling\c[0]: Wirklich?
'''
patched = '''
\c[10]Rookie Postman\c[0]: Really?
'''

[[dialogue]]
event = 9
page = 1
command = 18
original = '''
\c[10]Postboten\c[0]: Ja,\. das heißt zumindest im Sommer.\. Dann 
ist es nämlich so unerträglich heiß dort im 
Lagerraum, dass wir es uns draußen auf der Wiese 
gemütlich machen!
'''
patched = '''
\c[10]Postman\c[0]: Yeah,\. I mean in the summer at least.\.
Then it becomes so unbearably hot in the storage
room that we end up making ourselves comfortable
on the meadow!
'''

[[dialogue]]
event = 9
page = 1
command = 25
original = '''
\c[10]Postboten-Neuling\c[0]: ...\. Sehr witzig.
'''
patched = '''
\c[10]Rookie Postman\c[0]: Hah hah,\. very funny...\.
Give me a break.
'''

[[dialogue]]
event = 10
page = 1
command = 2
original = '''
\c[10]Postbote\c[0]: So einen ordentlichen Lager- und 
Aufenthaltsraum findet man nur in wenigen Post-
Versandstellen.\. Die in Ferrolholm hatte ich noch 
ganz ordentlich in Erinnerung.
'''
patched = '''
\c[10]Postbote\c[0]: Such a tidy storage room and lounge can
only be found in a few post offices.\. I remembered
the one in Ferrolholm quite well.
'''
