[[dialogue]]
event = 6
page = 1
command = 49
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Sie haben den Friedensvertrag 
unterzeichnet.
'''
patched = '''
\c[10]????\c[0]:\s[1] They signed the peace treaty.
'''

[[dialogue]]
event = 6
page = 1
command = 57
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Gut, \.damit sollte sich dieser 
Streit unter den Machthungrigen 
erstmal gelegt haben. \.Hoffen wir, 
dass uns genug Zeit bleibt...
'''
patched = '''
\c[10]????\c[0]:\s[1] Good,\. this should put
an end to this dispute among the
power-hungry.\. Let's just hope
we have enough time...
'''

[[dialogue]]
event = 6
page = 1
command = 62
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Momentan liegt all unsere 
Hoffnung in einem Kind, einer 
zerbrechlichen Figur, die an ihrer 
eigenen Trauer zugrunde geht.
'''
patched = '''
\c[10]????\c[0]:\s[1] Right now, all of our hope is
in a child, a fragile figure who's
still suffering from his misery.
'''

[[dialogue]]
event = 6
page = 1
command = 67
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Wir können nur Hoffen, dass 
die Zeiten des Friedens und der 
Segen von Heimdall ihn aus seiner 
Lage befreien werden.
'''
patched = '''
\c[10]????\c[0]:\s[1] We can only hope that this time
of peace and Heimdall's blessings
will free him from his grief.
'''

[[dialogue]]
event = 6
page = 1
command = 76
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Wieso können wir ihn nicht 
zur Seite stehen,\. uns direkt um ihn 
sorgen?
'''
patched = '''
\c[10]????\c[0]:\s[1] Why can't we just stay by his
side and help him out directly?
'''

[[dialogue]]
event = 6
page = 1
command = 85
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Wir können das Schicksal 
nicht lenken.
'''
patched = '''
\c[10]????\c[0]:\s[1] We cannot control fate.
'''

[[dialogue]]
event = 6
page = 1
command = 89
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Versuch es zu kontrollieren 
und es verschluckt dich,\. macht dich 
zu seinem Eigen\. und kontrolliert 
dich schließlich selbst.
'''
patched = '''
\c[10]????\c[0]:\s[1] Try to control it and it
swallows you,\. makes you its own,\.
and finally takes control of you.
'''

[[dialogue]]
event = 6
page = 1
command = 93
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Heimdall aber steht über all 
dem.\. Nur unter seiner Führung können 
wir das düstere Schicksal dieser 
Welt brechen.
'''
patched = '''
\c[10]????\c[0]:\s[1] Heimdall is above all of that.\.
Only under his leadership can we
prevent the gloomy fate that
awaits this world.
'''

[[dialogue]]
event = 6
page = 1
command = 104
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Und was sollen wir dann tun? \.
Beobachten und Warten?
'''
patched = '''
\c[10]????\c[0]:\s[1] Then what should we do?\.
Watch and wait?
'''

[[dialogue]]
event = 6
page = 1
command = 110
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Beobachten und Warten.\. Warten 
bis der Moment gekommen ist...
'''
patched = '''
\c[10]????\c[0]:\s[1] Watch and wait.\.
Wait for the moment to come...
'''

[[dialogue]]
event = 6
page = 1
command = 124
has_portrait = true
original = '''
\c[10]????\c[0]:\s[1] Der Moment an dem wir die 
Zwillingsseelen zusammenführen und 
der Welt ihren Befreier schenken.
'''
patched = '''
\c[10]????\c[0]:\s[1] The moment when the
twin souls reunite and give the
world their liberator.
'''
