[[dialogue]]
event = 5
page = 1
command = 2
original = '''
\c[10]Adelsfrau\c[0]: Mein Mann arbeitet die ganze Zeit an 
seinen Projekten. Man kann nicht richtig mit 
ihm reden. Mit den Gedanken ist er immer 
woanders....
'''
patched = '''
\c[10]Noblewoman\c[0]: My husband works on his projects
all the time. You can't really talk to him.
His thoughts are always somewhere else...
'''
