[[dialogue]]
event = 43
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Hinter diesem Durchgang wirst du 
wahrscheinlich kaum noch Erz finden. Für die Größe 
ist dort einfach immer zuviel Betrieb...
'''
patched = '''
\c[10]Prisoner\c[0]: You'll hardly find any ore behind that
opening. There's always too much going on for
that small of an area...
'''

[[dialogue]]
event = 44
page = 1
command = 2
original = '''
\c[10]Gefangene\c[0]: Dies ist der einzige Bereich in dem ich 
mich relativ wohl fühl.\. Hier ist die Höhle schön 
groß und weit...\. In den anderen Bereichen bekomme 
ich immer Platzangst...
'''
patched = '''
\c[10]Prisoner\c[0]: This is the only area where I feel even
slightly comfortable.\. Here, the cave is nice and
big...\. In the other areas, I always get
claustrophobia...
'''

[[dialogue]]
event = 45
page = 1
command = 4
original = '''
\c[10]Gefangener\c[0]: Dieser Erz-Abbau-Bereich ist was für 
Kletterbegeisterte, für die keine Höhe hoch genug 
ist.\. Ich meine,\. schau dir nur mal diese Verrückten 
da oben an!
'''
patched = '''
\c[10]Prisoner\c[0]: This area of the mine is for climbing
enthusiasts, those for who no height is high
enough.\. I mean,\. just look at those crazy
people up there!
'''

[[dialogue]]
event = 45
page = 1
command = 20
has_portrait = true
character = '''Cibon'''
original = '''
\c[2]\n[2]\c[0]: Juhu!\. Klippen!\. Los lass uns 
ganz nach oben klettern, Kumpel!
'''
patched = '''
\c[2]\n[2]\c[0]: Yeah!\. Cliffs!\. Let's go to the
top, Kento!
'''

[[dialogue]]
event = 45
page = 1
command = 28
has_portrait = true
character = '''Kento'''
original = '''
\c[1]\n[1]\c[0]: Wie kannst du in so einer 
Situation bloß so eine Begeisterung 
rausschlagen?
'''
patched = '''
\c[1]\n[1]\c[0]: How can you gather this
enthusiasm in such a situation?
'''

[[dialogue]]
event = 45
page = 1
command = 33
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Wahrscheinlich der Trieb eines 
Entdeckers. 
'''
patched = '''
\c[13]\n[3]\c[0]: Probably an adventurer's drive.
'''

[[dialogue]]
event = 45
page = 1
command = 36
has_portrait = true
character = '''Soko'''
original = '''
\c[13]\n[3]\c[0]: Mal sehen wie er sich in ein 
paar Wochen verhält, wenn uns jede 
Ecke der Mine bekannt ist.
'''
patched = '''
\c[13]\n[3]\c[0]: We'll see how well he does in a
few weeks when we know every corner
of the mine.
'''

[[dialogue]]
event = 46
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Da hoch?\. Nein danke, das ist mir zu 
gefährlich.\. Es ist nicht so, dass sich 
irgendjemand groß um dich kümmert, wenn du dir ein 
Bein brichst.
'''
patched = '''
\c[10]Prisoner\c[0]: Up there?\. No thanks, that's too
dangerous for me.\. It's not like anyone cares
about you if you break your leg.
'''

[[dialogue]]
event = 47
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: Ha, auch einer von denen, die ganz 
nach oben kommen?\. Schön, schön! \.Ich war schon 
früher begeisterter Bergsteigerer und ich mach es 
immer wieder gerne!
'''
patched = '''
\c[10]Prisoner\c[0]: Ha, you're also someone who can get to
the top?\. Good, good!\. I was an enthusiastic
mountaineer before and I'll always enjoy
being one!
'''

[[dialogue]]
event = 48
page = 1
command = 2
original = '''
\c[10]Gefangener\c[0]: ...\. Ich klettere immer bis hier nach 
oben, um Ruhe vor all den anderen Leuten zu haben, 
aber mittlerweile scheint das ja nicht mehr zu 
funktionieren...
'''
patched = '''
\c[10]Prisoner\c[0]: I always climb up here to stay calm in
front of all the other people, but now that
doesn't seem to work anymore...
'''

[[dialogue]]
event = 49
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 50
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 51
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 52
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 53
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 54
page = 1
command = 3
has_portrait = true
character = '''Kento'''
original = '''
(\c[1]\n[1]\c[0]: An der Stelle arbeitet 
bereits jemand. Es würde nur stören, 
wenn wir hier mithelfen.)
'''
patched = '''
(\c[1]\n[1]\c[0]: Looks like someone's already
working here. We'd only be disturbing
them if we tried to help out.)
'''

[[dialogue]]
event = 56
page = 2
command = 2
original = '''
\c[10]Wache\c[0]: Es gab tatsächlich Gefangene, die dachten, 
sie könnten sich zusammentun, sich in der Mine 
verschanzen und sich uns widersetzen.\. Nun, die
Vergangenheit hat gezeigt, dass das nicht hinhaut
'''
patched = '''
\c[10]Guard\c[0]: There were prisoners who actually thought
they could team up, stand together in the mine,
and oppose us.\. Well, the past has shown that
it doesn't work too well.
'''

[[dialogue]]
event = 56
page = 2
command = 6
original = '''
\c[10]Wache\c[0]: Im Endeffekt konnte keine Widerstandsgruppe 
standhalten, wenn wir vereint die Mine stürmten, 
um ihre Verschanzung zu brechen. Spitzhacke hält 
nicht gegen Langschwert, Speer und Bogen.
'''
patched = '''
\c[10]Guard\c[0]: Ultimately, no resistance group could stand
up to us if we stormed the mine together to break
their defense. Pickaxes don't hold out against
swords, spears, and bows.
'''

[[dialogue]]
event = 56
page = 2
command = 10
original = '''
\c[10]Wache\c[0]: Aber was red ich mit euch darüber?\. Geht 
sofort zurück zur Arbeit!
'''
patched = '''
\c[10]Guard\c[0]: But why am I even talking to you?\. Get back
to work immediately!
'''
